Ext.define('sencha-touch-app.controller.contacts.List', {
    extend: 'Ext.app.Controller',
    require: [
        'sencha-touch-app.view.contacts.Navigation',
        'sencha-touch-app.view.contacts.NewButton',
        'sencha-touch-app.view.contacts.List',
        'sencha-touch-app.view.contacts.New',
        'sencha-touch-app.view.contacts.Detail'
    ],

    config: {
        refs: {
            // referencies
            contactsNavigation: 'contactsNavigation',
            contactNewButton: 'contactNewButton',
            list: 'contactsList',
            contactDetail: 'contactDetail'
        },
        // fonctions / actions
        control: {
            contactNewButton: {
                tap: 'addNew'
            },
            list: {
                show: 'createNewButton',
                hide: 'removeNewButton',
                itemtap: 'showDetail'
            }
        }
    },

    addNew: function(dataview, index, target, record, e, options) {
        var self = this;

        // self.getContactsNavigation() is autogenerated when i refer xtype contactsNavigation
        var contactsNavigation = self.getContactsNavigation();

        // I'm create a new view
        var newView = Ext.create('sencha-touch-app.view.contacts.New');

        contactsNavigation.push(newView);
    },

    createNewButton: function(view, item) {
        var self = this;

        var contactsNavigation = self.getContactsNavigation();
        
        var newBtn = Ext.create('sencha-touch-app.view.contacts.NewButton');
        
        contactsNavigation.getNavigationBar().add(newBtn);
    },

    removeNewButton: function(view, item) {
        var self = this;
        // control that edit btn exist
        if(self.getContactNewButton()) 
        {
            self.getContactNewButton().destroy();
        }
    },

    showDetail: function(dataview, index, target, record, e, options) {
        var self = this;
        // self.getContactsNavigation() is autogenerated when i refer xtype contactsNavigation
        var contactsNavigation = self.getContactsNavigation();

        // I'm create a new view
        var detailView = Ext.create('sencha-touch-app.view.contacts.Detail');

        // Pass data
        detailView.setRecord(record);
        var data = record.getData();
        detailView.setData(data);

        // You need to add property 'title' in the view for being settable
        detailView.setTitle(data.firstName);

        // push the new detail View
        contactsNavigation.push(detailView);
    }
});
